For the first time in history, we are able to return back to a functions execution context after we've left it.
